# Generated by Django 4.1 on 2023-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookid', models.IntegerField()),
                ('BookName', models.TextField()),
                ('Author', models.TextField()),
                ('Publication', models.TextField()),
                ('CreateAt', models.DateField()),
                ('UpdateAt', models.DateField()),
            ],
        ),
    ]
