# Generated by Django 4.1 on 2023-02-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksInfo',
            new_name='Book',
        ),
    ]
